### YAML Anchors
fetch: &fetch
  type: http
  interval: 43200 # 12 hours
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 600 # 10 minutes

use: &use
  type: select
  use:
    - flyairport
    - efcloud
    - kogeki
    - spcloud

use-backup: &use-backup
  type: select
  use:
    - pawdroid
    - ermaozi
    #- jsnzkpg

port: 7890
external-controller: 127.0.0.1:9090
log-level: warning
unified-delay: true
tcp-concurrent: true
geodata-mode: true

proxy-groups:
  - { name: PROXY, type: select, proxies: [自动选择, 备用自动选择, DIRECT] }
  - { name: 自动选择, <<: *use, tolerance: 2, type: url-test }
  - { name: 备用自动选择, <<: *use-backup, tolerance: 2, type: url-test }

  # 分隔,下面是地区分组
  #- { name: 香港, <<: *use, type: url-test, filter: "(?i)港|hk|hongkong|hong kong" }
  - { name: 台湾, <<: *use, type: url-test, filter: "(?i)台|tw|taiwan" }
  #- { name: 日本, <<: *use, type: url-test, filter: "(?i)日本|jp|japan" }
  #- { name: 美国, <<: *use, type: url-test, filter: "(?i)美|us|unitedstates|united states" }
  #- { name: 新加坡, <<: *use, type: url-test, filter: "(?i)(新|sg|singapore)" }

rules:
  ### WHITELIST
  # FILTER
  - GEOIP,   lan,               DIRECT, no-resolve
  - GEOSITE, private,           DIRECT
  - GEOSITE, category-ads,      REJECT

  # DIRECT
  - DOMAIN-SUFFIX, envs.net,      DIRECT
  - DOMAIN-SUFFIX, catgirl.cloud, DIRECT
  - GEOSITE, freecodecamp,      DIRECT # music radio
  - GEOSITE, icloud,            DIRECT
  - GEOSITE, apple@cn,          DIRECT
  - GEOSITE, google@cn,         DIRECT
  - GEOSITE, microsoft@cn,      DIRECT
  - GEOSITE, category-games@cn, DIRECT

  # PROXY
  - GEOSITE, spotify,           台湾
  # - GEOSITE, google,            PROXY
  # - GEOSITE, telegram,          PROXY

  # NOMATCH
  - GEOSITE, cn,                DIRECT
  - GEOIP,   cn,                DIRECT
  - MATCH,                      PROXY
