### YAML Anchors
fetch: &fetch
  type: http
  interval: 3600
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300

use: &use
  type: select
  use:
    - efcloud
    - spcloud

use-backup: &use-backup
  type: select
  use:
    - pawdroid
    - ermaozi
    #- jsnzkpg

allow-lan: true
port: 7890
unified-delay: true
tcp-concurrent: true
external-controller: 127.0.0.1:9090
log-level: warning

geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

proxy-groups:
  - { name: PROXY, type: select, proxies: [自动选择, 备用自动选择, DIRECT] }

  - { name: 自动选择, <<: *use, tolerance: 2, type: url-test }
  - { name: 备用自动选择, <<: *use-backup, tolerance: 2, type: url-test }

  # 分隔,下面是地区分组
  #- { name: 香港, <<: *use, type: url-test, filter: "(?i)港|hk|hongkong|hong kong" }
  - { name: 台湾, <<: *use, type: url-test, filter: "(?i)台|tw|taiwan" }
  #- { name: 日本, <<: *use, type: url-test, filter: "(?i)日本|jp|japan" }
  #- { name: 美国, <<: *use, type: url-test, filter: "(?i)美|us|unitedstates|united states" }
  #- { name: 新加坡, <<: *use, type: url-test, filter: "(?i)(新|sg|singapore)" }

rules:
  - GEOIP,   lan,       DIRECT, no-resolve
  - GEOSITE, bilibili,  DIRECT
  - GEOSITE, spotify,   台湾
  - GEOSITE, CN,        DIRECT
  - GEOIP,   CN,        DIRECT

  # 未匹配到任何规则
  - MATCH, PROXY
