### YAML Anchors
fetch: &fetch
  type: http
  interval: 3600
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 300

use: &use
  type: select
  use:
    - kogeki
    - efcloud
    - spcloud

use-backup: &use-backup
  type: select
  use:
    - pawdroid
    - ermaozi
    #- jsnzkpg

port: 7890
external-controller: 127.0.0.1:9090
log-level: warning
unified-delay: true
tcp-concurrent: true
geodata-mode: true

proxy-groups:
  - { name: PROXY, type: select, proxies: [自动选择, 备用自动选择, DIRECT, lon0] }
  - { name: 自动选择, <<: *use, tolerance: 2, type: url-test }
  - { name: 备用自动选择, <<: *use-backup, tolerance: 2, type: url-test }

  # 分隔,下面是地区分组
  #- { name: 香港, <<: *use, type: url-test, filter: "(?i)港|hk|hongkong|hong kong" }
  - { name: 台湾, <<: *use, type: url-test, filter: "(?i)台|tw|taiwan" }
  #- { name: 日本, <<: *use, type: url-test, filter: "(?i)日本|jp|japan" }
  #- { name: 美国, <<: *use, type: url-test, filter: "(?i)美|us|unitedstates|united states" }
  #- { name: 新加坡, <<: *use, type: url-test, filter: "(?i)(新|sg|singapore)" }

rules:
  - GEOIP,   lan,           DIRECT, no-resolve
  - GEOSITE, category-ads,  REJECT
  - GEOSITE, spotify,       台湾
  - GEOIP,   cn,            DIRECT
  - GEOSITE, cn,            DIRECT

  # 未匹配到任何规则
  - MATCH, PROXY
