[files]
extend-exclude = [
  "secrets.yaml",

  # hex color
  "home/applications/swaylock/default.nix",
]

[default.extend-words]
# osu
lazer = "lazer"

# https://en.wikipedia.org/wiki/IATA_airport_code
tyo = "tyo"
