### YAML Anchors
fetch: &fetch
  type: http
  interval: 43200 # 12 hours
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 600 # 10 minutes

use: &use
  type: select
  use:
    - efcloud
    - flyairport
    - spcloud

port: 7890
external-controller: 127.0.0.1:9090
log-level: warning
unified-delay: true
tcp-concurrent: true
geodata-mode: true

secret: "@clash/secret@"

proxies:
  # @clash/proxies/lightsail@

proxy-providers:
  efcloud:
    <<: *fetch
    url: "@clash/proxy-providers/efcloud@"
  flyairport:
    <<: *fetch
    url: "@clash/proxy-providers/flyairport@"
  spcloud:
    <<: *fetch
    url: "@clash/proxy-providers/spcloud@"

proxy-groups:
  - { name: PROXY, type: select, proxies: [自动选择, lightsail, DIRECT] }
  - { name: 自动选择, <<: *use, tolerance: 2, type: url-test }

rules:
  - GEOIP,   lan,               DIRECT, no-resolve
  - GEOSITE, private,           DIRECT
  - GEOSITE, category-ads,      REJECT

  - GEOSITE, icloud,            DIRECT
  - GEOSITE, apple@cn,          DIRECT
  - GEOSITE, google@cn,         DIRECT
  - GEOSITE, microsoft@cn,      DIRECT
  - GEOSITE, category-games@cn, DIRECT

  - GEOSITE, cn,                DIRECT
  - GEOIP,   cn,                DIRECT
  - MATCH,                      PROXY
