#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x feh > /dev/null || feh --bg-fill /home/guanranwang/.local/share/backgrounds/wallpaper1.png

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         2
bspc config window_gap           4
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true